[package]
name = "APTRaidersGame"
version = "1.0.0"
license = "MIT"
authors = []

[addresses]
publisher = "0x5ba9fa393e4840013932ecceb243ae2e6c38a558444fe777ebe8e0550c4c4e18"

[dev-addresses]
publisher = "0x5ba9fa393e4840013932ecceb243ae2e6c38a558444fe777ebe8e0550c4c4e18"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dev-dependencies]
